Fixing missing dependency while parsing a file extracted from an archive (Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/adapters/HexBinaryAdapter)